### ISSUE TITLE
Error: handle is not a Buffer

### ISSUE THREAD

**Issue by xiaoyann** [xiaoyann/deploy-kit#1]
/Users/xiaofeng/working/jinyinwu/official-website/jinyinwu/frontend/node_modules/ssh2-streams/lib/sftp.js:879
    throw new Error('handle is not a Buffer');
    ^

Error: handle is not a Buffer
    at SFTPStream.writeData (/Users/xiaofeng/working/jinyinwu/official-website/jinyinwu/frontend/node_modules/ssh2-streams/lib/sftp.js:879:11)
    at SFTPWrapper.write (/Users/xiaofeng/working/jinyinwu/official-website/jinyinwu/frontend/node_modules/ssh2/lib/SFTPWrapper.js:48:23)
    at /Users/xiaofeng/working/jinyinwu/official-website/jinyinwu/frontend/node_modules/scp2/lib/client.js:195:16
    at iterate (/Users/xiaofeng/working/jinyinwu/official-website/jinyinwu/frontend/node_modules/scp2/node_modules/async/lib/async.js:146:13)
    at Object.async.eachSeries (/Users/xiaofeng/working/jinyinwu/official-website/jinyinwu/frontend/node_modules/scp2/node_modules/async/lib/async.js:162:9)
    at _write (/Users/xiaofeng/working/jinyinwu/official-website/jinyinwu/frontend/node_modules/scp2/lib/client.js:193:15)
    at /Users/xiaofeng/working/jinyinwu/official-website/jinyinwu/frontend/node_modules/scp2/lib/client.js:244:11
    at SFTPStream._transform (/Users/xiaofeng/working/jinyinwu/official-website/jinyinwu/frontend/node_modules/ssh2-streams/lib/sftp.js:387:17)
    at SFTPStream.Transform._read (_stream_transform.js:167:10)
    at SFTPStream._read (/Users/xiaofeng/working/jinyinwu/official-website/jinyinwu/frontend/node_modules/ssh2-streams/lib/sftp.js:170:15)
    at SFTPStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:333:12)
    at writeOrBuffer (_stream_writable.js:319:5)
    at SFTPStream.Writable.write (_stream_writable.js:246:11)
    at Channel.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by xiaoyann** [comment]
目标服务器上对该文件没有写权限
